[project]
name = "clickhouse-keeper-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathspec==0.12.1",
    "prometheus-client==0.22.1",
    "pyyaml==6.0.2",
    "yamllint==1.37.1",
]
